### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by yzinets** [ValvePython/csgo#12]
Code:
```
from steam import SteamClient
from csgo import CSGOClient
from csgo.enums import ECsgoGCMsg

steam_client = SteamClient()
steam_client.anonymous_login()
client = CSGOClient(steam_client)
client.launch()

client.send(
    ECsgoGCMsg.EMsgGCCStrike15_v2_Client2GCEconPreviewDataBlockRequest,
    data={
        "s": 76561198390812765,
        "a": 11899154096,
        "d": 14908795644343063777
    }
)
```
Traceback:
```
Traceback (most recent call last):
  File "/home/yzinets/Projects/python-steam/run.py", line 15, in <module>
    "d": 14908795644343063777
  File "/usr/local/lib/python3.5/dist-packages/csgo/client.py", line 173, in send
    self._send(emsg, data, proto)
  File "/usr/local/lib/python3.5/dist-packages/csgo/client.py", line 186, in _send
    proto_fill_from_dict(message, data)
  File "/usr/local/lib/python3.5/dist-packages/steam/util/__init__.py", line 111, in proto_fill_from_dict
    desc = field_descs[key]
KeyError: 'a'
```

**Comment by rossengeorgiev** [comment]
It means that message doesn't have those variable names. See:

https://github.com/ValvePython/csgo/blob/4024625fe347ac0aadd5b2222e66af71ede1f5cc/csgo/features/items.py#L38-L43
