### ISSUE TITLE
Minimal code given in the docs returns AttributeError: EMsgGCCStrike15_v2_SetMyMedalsInfo

### ISSUE THREAD

**Issue by aytugdemir** [ValvePython/csgo#17]
My code:

```python
from steam import SteamClient
from csgo import CSGOClient

client = SteamClient()
cs = CSGOClient(client)

@client.on('logged_on')
def start_csgo():
    cs.launch()

@cs.on('ready')
def gc_ready():
    # send messages to gc
    pass

client.cli_login('username', 'password')
client.run_forever()
```

Output:

```
MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.util.ssl_ (C:\\Users\\moros\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\urllib3\\util\\ssl_.py)', 'urllib3.util (C:\\Users\\moros\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\urllib3\\util\\__init__.py)']. 
  _warnings)
Traceback (most recent call last):
  File "C:/Users/moros/Desktop/python/bot.py", line 5, in <module>
    cs = CSGOClient(client)
  File "C:\Users\moros\AppData\Local\Programs\Python\Python37-32\lib\site-packages\csgo\__init__.py", line 11, in __new__
    from csgo.client import CSGOClient as CSC
  File "C:\Users\moros\AppData\Local\Programs\Python\Python37-32\lib\site-packages\csgo\client.py", line 15, in <module>
    from csgo.msg import get_emsg_enum, find_proto
  File "C:\Users\moros\AppData\Local\Programs\Python\Python37-32\lib\site-packages\csgo\msg.py", line 75, in <module>
    ECsgoGCMsg.EMsgGCCStrike15_v2_SetMyMedalsInfo: cstrike15_gcmessages_pb2.PlayerMedalsInfo,
  File "C:\Users\moros\AppData\Local\Programs\Python\Python37-32\lib\enum.py", line 349, in __getattr__
    raise AttributeError(name) from None
AttributeError: EMsgGCCStrike15_v2_SetMyMedalsInfo
```

**Comment by rossengeorgiev** [comment]
Thanks for the report. Just update the package to get the fix.
