### ISSUE TITLE
keyerror in request_preview_data_block

### ISSUE THREAD

**Issue by VVILD** [ValvePython/csgo#4]
i am trying to fetch the item_data_block of an item in my inventory

what i am trying:

`@cs.on('ready')
def gc_ready():

	cs.request_preview_data_block(76561198135880269, 9047986951, 16351671827548572774, 0)

	ds,=cs.wait_event('item_data_block')

	print ds
`

my error

`
Traceback (most recent call last):
  File "/Users/sargungulati/Desktop/pricebaap/main/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "csrr.py", line 28, in gc_ready
    cs.request_preview_data_block(76561198135880269, 9047986951, 16351671827548572774, 0)
  File "/Users/sargungulati/Desktop/pricebaap/main/lib/python2.7/site-packages/csgo/features/items.py", line 42, in request_preview_data_block
    'm': m,
  File "/Users/sargungulati/Desktop/pricebaap/main/lib/python2.7/site-packages/csgo/client.py", line 173, in send
    self._send(emsg, data, proto)
  File "/Users/sargungulati/Desktop/pricebaap/main/lib/python2.7/site-packages/csgo/client.py", line 186, in _send
    proto_fill_from_dict(message, data)
  File "/Users/sargungulati/Desktop/pricebaap/main/lib/python2.7/site-packages/steam/util/__init__.py", line 111, in proto_fill_from_dict
    desc = field_descs[key]
KeyError: 'a'

Sat Feb 11 16:38:55 2017 <Greenlet at 0x10919d4b0: gc_ready> failed with KeyError
`

**Comment by rossengeorgiev** [comment]
Thank for the report
