### ISSUE TITLE
AttributeError: 'Match' object has no attribute 'on'

### ISSUE THREAD

**Issue by SaimM95** [ValvePython/csgo#5]
Getting this error when creating a new Match object by calling `match.Match()`

Full stacktrace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "abc.py", line 36, in gc_ready
    sengMsg()
  File "abc.py", line 14, in sengMsg
    matchObj = match.Match()
  File "/usr/local/lib/python3.5/site-packages/csgo/features/match.py", line 8, in __init__
    self.on(ECsgoGCMsg.EMsgGCCStrike15_v2_MatchmakingGC2ClientHello, self.__handle_mmstats)
AttributeError: 'Match' object has no attribute 'on'
```

**Comment by rossengeorgiev** [comment]
That class is a base for `CSGOClient`. It is not intended to be used on its' own.
